-- Create the questions table
create table public.questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  category text default 'relationship' not null check (category in ('self', 'relationship')),
  is_opened boolean default false not null
);

-- For existing projects that already created the table before categories existed:
alter table public.questions
  add column if not exists category text default 'relationship'
  check (category in ('self', 'relationship'));

-- Enable Row Level Security
alter table public.questions enable row level security;

-- Create policies (Allow anon read and insert)
create policy "Allow anon read access"
  on public.questions
  for select
  to anon
  using (true);

create policy "Allow anon insert access"
  on public.questions
  for insert
  to anon
  with check (true);

create policy "Allow anon update access"
  on public.questions
  for update
  to anon
  using (true);
